import notificationContent from "./content.json";

export const notificationSamplePreview = {
  doc_no: "TRAC-2609001",
  doc_date: "01 กันยายน 2569 / September 01, 2026",
  recipient: "ท่านคู่ค้าและลูกค้าผู้มีอุปการคุณ / Valued Business Partners",
  subject: "แจ้งเปลี่ยนแปลงที่อยู่สำนักงานใหญ่ / Change of Head Office Address",
  effective_date: "16 กันยายน 2569",
  effective_date_en: "September 16, 2026",
  effective_date_badge: "(มีผล 16 ก.ย. 2569 / Effective Sept 16, 2026):",
  old_address_th: "45 ซอยโกสุมรวมใจ 37 แขวงดอนเมือง เขตดอนเมือง กรุงเทพมหานคร 10210",
  old_address_en: "45 Soi Kosum Ruam Chai 37, Don Mueang, Don Mueang, Bangkok 10210, Thailand",
  new_address_th: "18 ซอยโกสุมรวมใจ 35 แยก 4 แขวงดอนเมือง เขตดอนเมือง กรุงเทพมหานคร 10210",
  new_address_en: "18 Soi Kosum Ruam Chai 35 Yaek 4, Don Mueang, Don Mueang, Bangkok 10210, Thailand",
  signatory_name: "นายศรายุทธ  โกสิยารักษ์",
  signatory_position: "กรรมการผู้จัดการ / CEO",
};

export const notificationTemplate = {
  id: "notification",
  type: "letter",
  profileSchemaId: "notification",
  name: "Notification Letter",
  fullName: "หนังสือแจ้งเปลี่ยนแปลงที่ตั้งสำนักงานใหญ่",
  logo: "/header_logo.png",
  pageCount: 1,
  hasHeader: false,
  hasFooter: false,
  content: notificationContent,
  previewData: notificationSamplePreview,
  defaultValues: {},

  companyInfo: {
    nameTh: "บริษัท เดอะ รีโคฟเวอรี่ แอดไวเซอร์ จำกัด",
    nameEn: "THE RECOVERY ADVISOR CO., LTD.",
    taxId: "0105554007189",
    phone: "02-1019884",
    address: "45 ซอยโกสุมรวมใจ 37 แขวงดอนเมือง เขตดอนเมือง กรุงเทพมหานคร 10210",
    signatoryName: "นายศรายุทธ  โกสิยารักษ์",
    signatoryPosition: "กรรมการผู้จัดการ / CEO",
  },

  fields: [
    {
      id: "doc_no",
      sharedKey: "notification_doc_no",
      label: "เลขที่เอกสาร (Doc No.)",
      type: "text",
      page: 1,
      placeholder: "TRAC-2609001",
      required: false,
    },
    {
      id: "doc_date",
      sharedKey: "notification_doc_date",
      label: "วันที่ออกเอกสาร (Date)",
      type: "text",
      page: 1,
      placeholder: "01 กันยายน 2569 / September 01, 2026",
      required: true,
    },
    {
      id: "recipient",
      sharedKey: "notification_recipient",
      label: "เรียน / ผู้รับ (To / Recipient)",
      type: "text",
      page: 1,
      placeholder: "ท่านคู่ค้าและลูกค้าผู้มีอุปการคุณ / Valued Business Partners",
      required: true,
    },
    {
      id: "subject",
      sharedKey: "notification_subject",
      label: "เรื่อง (Subject)",
      type: "text",
      page: 1,
      placeholder: "แจ้งเปลี่ยนแปลงที่อยู่สำนักงานใหญ่ / Change of Head Office Address",
      required: true,
    },
    {
      id: "effective_date",
      sharedKey: "notification_effective_date",
      label: "วันที่มีผลบังคับใช้ (ไทย)",
      type: "text",
      page: 1,
      placeholder: "16 กันยายน 2569",
      required: true,
    },
    {
      id: "effective_date_en",
      sharedKey: "notification_effective_date_en",
      label: "วันที่มีผลบังคับใช้ (อังกฤษ)",
      type: "text",
      page: 1,
      placeholder: "September 16, 2026",
      required: true,
    },
    {
      id: "old_address_th",
      sharedKey: "notification_old_address_th",
      label: "ที่อยู่เดิม (ไทย)",
      type: "textarea",
      page: 1,
      placeholder: "45 ซอยโกสุมรวมใจ 37 แขวงดอนเมือง เขตดอนเมือง กรุงเทพมหานคร 10210",
      required: true,
    },
    {
      id: "old_address_en",
      sharedKey: "notification_old_address_en",
      label: "Previous Address (EN)",
      type: "textarea",
      page: 1,
      placeholder: "45 Soi Kosum Ruam Chai 37, Don Mueang, Don Mueang, Bangkok 10210, Thailand",
      required: true,
    },
    {
      id: "new_address_th",
      sharedKey: "notification_new_address_th",
      label: "ที่อยู่ใหม่ (ไทย)",
      type: "textarea",
      page: 1,
      placeholder: "18 ซอยโกสุมรวมใจ 35 แยก 4 แขวงดอนเมือง เขตดอนเมือง กรุงเทพมหานคร 10210",
      required: true,
    },
    {
      id: "new_address_en",
      sharedKey: "notification_new_address_en",
      label: "New Address (EN)",
      type: "textarea",
      page: 1,
      placeholder: "18 Soi Kosum Ruam Chai 35 Yaek 4, Don Mueang, Don Mueang, Bangkok 10210, Thailand",
      required: true,
    },
    {
      id: "signatory_name",
      sharedKey: "notification_signatory_name",
      label: "ชื่อผู้ลงนาม",
      type: "text",
      page: 1,
      placeholder: "นายศรายุทธ  โกสิยารักษ์",
      required: true,
    },
    {
      id: "signatory_position",
      sharedKey: "notification_signatory_position",
      label: "ตำแหน่งผู้ลงนาม",
      type: "text",
      page: 1,
      placeholder: "กรรมการผู้จัดการ / CEO",
      required: true,
    },
  ],
};
