/**
 * 📚 DocBuilder Canonical Template & Category Catalog
 * Single Source of Truth for system categories and built-in templates.
 */

import {
  getNdaBlocks,
  getPartnerBlocks,
  getDistributorBlocks,
} from "./contractBlocksBuilder.js";

export const SYSTEM_CATEGORIES = [
  {
    id: "quotation",
    name: "Quotation",
    fullName: "ใบเสนอราคา",
    description: "ใบเสนอราคาพร้อมรายการสินค้า/บริการ คำนวณภาษี VAT 7% และยอดรวมอัตโนมัติ",
    icon: "Receipt",
    color: "purple",
    badge: "มาตรฐาน",
    order: 1,
    href: "/create/quotation",
    available: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "nda",
    name: "NDA",
    fullName: "หนังสือสัญญาไม่เปิดเผยข้อมูล",
    description: "Non-Disclosure Agreement สัญญามาตรฐานสำหรับการรักษาความลับทางการค้า",
    icon: "FileSignature",
    color: "blue",
    badge: "มาตรฐาน",
    order: 2,
    href: "/create/nda",
    available: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "partner",
    name: "Partner Agreement",
    fullName: "สัญญาแต่งตั้งพันธมิตรตัวแทนจำหน่าย",
    description: "สัญญาแต่งตั้งพันธมิตร พร้อมเงื่อนไข Deal Registration และอัตราแลกเปลี่ยน",
    icon: "Handshake",
    color: "emerald",
    badge: "มาตรฐาน",
    order: 3,
    href: "/create/partner",
    available: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "distributor",
    name: "Distributor Agreement",
    fullName: "สัญญาแต่งตั้งและจัดจำหน่ายซอฟต์แวร์",
    description: "สัญญาแต่งตั้งตัวแทนจำหน่ายและจัดจำหน่ายซอฟต์แวร์",
    icon: "Building2",
    color: "indigo",
    badge: "มาตรฐาน",
    order: 4,
    href: "/create/distributor",
    available: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "notification",
    name: "Notification Letter",
    fullName: "หนังสือแจ้งและประกาศทางการ",
    description: "หนังสือแจ้งการ, จดหมายแจ้งเปลี่ยนแปลงข้อมูลองค์กร และประกาศทางการ",
    icon: "Megaphone",
    color: "rose",
    badge: "มาตรฐาน",
    order: 5,
    href: "/create/notification",
    available: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];

export const SYSTEM_SUB_TEMPLATES = {
  quotation: [
    {
      id: "quotation-standard",
      categoryId: "quotation",
      name: "ใบเสนอราคามาตรฐาน",
      englishName: "CREST ZENDO Quotation",
      tag: "มาตรฐาน",
      tagColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
      description: "เทมเพลตใบเสนอราคามาตรฐานของ CREST ZENDO พร้อมระบบคำนวณ VAT 7% และส่วนลดอัตโนมัติ",
      pageCount: "ไดนามิก (ตามรายการสินค้า)",
      features: [
        "คำนวณ VAT 7% และส่วนลดอัตโนมัติ",
        "รองรับการเพิ่ม/ลบรายการและหมวดหมู่ย่อย",
        "สร้างเลข Quotation No. อัตโนมัติ",
        "ส่งออกเป็น PDF และส่งอีเมลได้ทันที",
      ],
    },
  ],
  nda: [
    {
      id: "nda-standard",
      categoryId: "nda",
      name: "หนังสือสัญญาไม่เปิดเผยข้อมูล",
      englishName: "Non-Disclosure Agreement (NDA)",
      tag: "มาตรฐาน",
      tagColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
      description: "หนังสือสัญญาไม่เปิดเผยข้อมูลมาตรฐานสำหรับการรักษาความลับทางการค้าและทรัพย์สินทางปัญญา",
      pageCount: "4 หน้า",
      features: [
        "คุ้มครองข้อมูลความลับทางการค้าและเทคโนโลยี",
        "ข้อกำหนดการรักษาความลับและการลงนามทั้งสองฝ่าย",
        "ส่งออกเป็น PDF พร้อมใช้งาน",
      ],
    },
  ],
  partner: [
    {
      id: "partner-standard",
      categoryId: "partner",
      name: "สัญญาแต่งตั้งพันธมิตรตัวแทนจำหน่าย",
      englishName: "Partner Agreement",
      tag: "มาตรฐาน",
      tagColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
      description: "สัญญาแต่งตั้งพันธมิตรตัวแทนจำหน่าย พร้อมเงื่อนไข Deal Registration และอัตราแลกเปลี่ยน",
      pageCount: "5 หน้า",
      features: [
        "เงื่อนไข Deal Registration ปกป้องโอกาสทางการขาย",
        "อัตราส่วนลดมาตรฐานของตัวแทนและเงื่อนไขความร่วมมือ",
        "ส่งออกเป็น PDF พร้อมใช้งาน",
      ],
    },
  ],
  distributor: [
    {
      id: "distributor-standard",
      categoryId: "distributor",
      name: "สัญญาแต่งตั้งและจัดจำหน่ายซอฟต์แวร์",
      englishName: "Distributor Agreement",
      tag: "มาตรฐาน",
      tagColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
      description: "สัญญาแต่งตั้งตัวแทนจำหน่ายและจัดจำหน่ายซอฟต์แวร์",
      pageCount: "5 หน้า",
      features: [
        "สิทธิการจัดจำหน่ายในอาณาเขตที่กำหนด",
        "ข้อกำหนดการสั่งซื้อและการชำระเงิน",
        "ส่งออกเป็น PDF พร้อมใช้งาน",
      ],
    },
  ],
  notification: [
    {
      id: "tmpl-notification-standard",
      categoryId: "notification",
      name: "หนังสือแจ้งเปลี่ยนแปลงที่ตั้งสำนักงานใหญ่",
      englishName: "Notice of Head Office Relocation",
      tag: "มาตรฐาน",
      tagColor: "bg-rose-50 text-rose-700 border-rose-200",
      description: "หนังสือแจ้งเปลี่ยนแปลงที่อยู่และสถานที่ตั้งสำนักงานใหญ่ทางการ (ไทย-อังกฤษ)",
      pageCount: "1 หน้า",
      features: [
        "หนังสือแจ้งเปลี่ยนแปลงที่อยู่สองภาษา (TH/EN)",
        "กล่องเปรียบเทียบที่อยู่เดิมและที่อยู่ใหม่อย่างชัดเจน",
        "ส่วนลงนามผู้มีอำนาจลงนามและตำแหน่ง",
        "ส่งออกเป็น PDF คุณภาพสูงได้ทันที",
      ],
    },
  ],
};

export const SYSTEM_DEFAULT_TEMPLATES = [
  {
    id: "tmpl-quotation-standard",
    categoryId: "quotation",
    version: 1,
    name: "ใบเสนอราคามาตรฐาน",
    englishName: "Quotation Standard Template",
    description: "โครงสร้างเทมเพลตใบเสนอราคามาตรฐาน พร้อมระบบคำนวณภาษี VAT 7% และส่วนลด",
    icon: "Receipt",
    badge: "มาตรฐาน",
    pageCount: "1 หน้า A4",
    status: "published",
    orientation: "portrait",
    theme: { primaryColor: "#5542F6", backgroundColor: "#FFFFFF", hasWatermark: false },
    blocks: [
      {
        id: "b_header",
        type: "header",
        title: "หัวกระดาษบริษัท",
        settings: {
          hasLogo: true,
          logoUrl: "/quotation.png",
          companyName: "[ ชื่อบริษัท / ผู้เสนอราคา ]",
          companyNameEn: "[ Company Name (EN) ]",
          taxId: "0-0000-00000-00-0",
          address: "[ ที่อยู่สำนักงานใหญ่ / สถานประกอบการ ]",
          phone: "02-XXX-XXXX",
          email: "contact@company.com",
          align: "split",
        },
      },
      {
        id: "b_title",
        type: "doc_title",
        title: "หัวเรื่องเอกสาร",
        settings: {
          titleText: "ใบเสนอราคา (QUOTATION)",
          subtitleText: "ต้นฉบับ / Original",
          align: "center",
        },
      },
      {
        id: "b_info",
        type: "info_grid",
        title: "ข้อมูลลูกค้าและเอกสาร",
        settings: {
          billToTitle: "Bill To:",
          billToCompany: "[ ชื่อบริษัทลูกค้า / ผู้รับบริการ ]",
          attnName: "[ ชื่อผู้ติดต่อ ]",
          subject: "[ ระบุเรื่อง / โครงการ ]",
          quotationNo: "QT-YYYYMM-XXXX",
          date: "[ ว/ด/ป ที่ออกเอกสาร ]",
          validity: "30 วัน",
          amName: "[ ชื่อผู้จัดทำ / Account Manager ]",
        },
      },
      {
        id: "b_table",
        type: "quotation_table",
        title: "ตารางรายการสินค้า/บริการ",
        settings: {
          vatRate: 7,
          items: [],
        },
      },
      {
        id: "b_terms",
        type: "terms",
        title: "เงื่อนไขและข้อกำหนด",
        settings: {
          heading: "เงื่อนไขการชำระเงินและส่งมอบ:",
          bullets: [
            "ราคานี้ยังไม่รวมภาษีมูลค่าเพิ่ม (VAT 7%)",
            "กำหนดยืนราคา 30 วันนับจากวันที่ในเอกสาร",
            "เงื่อนไขการชำระเงิน: ภายใน 30 วันนับจากวันส่งมอบงาน",
          ],
        },
      },
      {
        id: "b_signatures",
        type: "signatures",
        title: "ส่วนลงนามอนุมัติ",
        settings: {
          slots: [
            { id: "s1", name: "[ ผู้มีอำนาจลงนาม / ผู้เสนอราคา ]", role: "ผู้เสนอราคา" },
            { id: "s2", name: "............................................", role: "ผู้อนุมัติสั่งซื้อ / ลูกค้า" },
          ],
        },
      },
    ],
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "tmpl-nda-standard",
    categoryId: "nda",
    version: 1,
    name: "หนังสือสัญญาไม่เปิดเผยข้อมูล",
    englishName: "Non-Disclosure Agreement (NDA)",
    description: "โครงสร้างสัญญามาตรฐานสำหรับการรักษาความลับทางการค้าและทรัพย์สินทางปัญญา",
    icon: "FileSignature",
    badge: "มาตรฐาน",
    pageCount: "4 หน้า A4",
    status: "published",
    orientation: "portrait",
    theme: { primaryColor: "#5542F6", backgroundColor: "#FFFFFF", hasWatermark: false },
    blocks: getNdaBlocks(),
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "tmpl-partner-standard",
    categoryId: "partner",
    version: 1,
    name: "สัญญาแต่งตั้งพันธมิตรตัวแทนจำหน่าย",
    englishName: "Partner Agreement",
    description: "โครงสร้างสัญญาแต่งตั้งพันธมิตรทางธุรกิจ พร้อมเงื่อนไข Deal Registration",
    icon: "Handshake",
    badge: "มาตรฐาน",
    pageCount: "5 หน้า A4",
    status: "published",
    orientation: "portrait",
    theme: { primaryColor: "#5542F6", backgroundColor: "#FFFFFF", hasWatermark: false },
    blocks: getPartnerBlocks(),
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "tmpl-distributor-standard",
    categoryId: "distributor",
    version: 1,
    name: "สัญญาแต่งตั้งและจัดจำหน่ายซอฟต์แวร์",
    englishName: "Distributor Agreement",
    description: "โครงสร้างสัญญาแต่งตั้งตัวแทนจำหน่ายและจัดจำหน่ายซอฟต์แวร์",
    icon: "Building2",
    badge: "มาตรฐาน",
    pageCount: "5 หน้า A4",
    status: "published",
    orientation: "portrait",
    theme: { primaryColor: "#5542F6", backgroundColor: "#FFFFFF", hasWatermark: false },
    blocks: getDistributorBlocks(),
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "tmpl-notification-standard",
    categoryId: "notification",
    version: 1,
    name: "หนังสือแจ้งเปลี่ยนแปลงที่ตั้งสำนักงานใหญ่",
    englishName: "Notice of Head Office Relocation",
    description: "หนังสือแจ้งการเปลี่ยนแปลงที่อยู่และสถานที่ตั้งสำนักงานใหญ่ทางการ (ไทย-อังกฤษ)",
    icon: "Megaphone",
    badge: "มาตรฐาน",
    pageCount: "1 หน้า A4",
    status: "published",
    orientation: "portrait",
    theme: { primaryColor: "#5542F6", backgroundColor: "#FFFFFF", hasWatermark: false },
    blocks: [
      {
        id: "b_header",
        type: "header",
        title: "หัวกระดาษ",
        settings: {
          hasLogo: true,
          logoUrl: "/header_logo.png",
          companyName: "บริษัท เดอะ รีโคฟเวอรี่ แอดไวเซอร์ จำกัด",
          companyNameEn: "THE RECOVERY ADVISOR CO., LTD.",
          taxId: "0105554007189",
          branch: "สำนักงานใหญ่",
          address: "45 ซอยโกสุมรวมใจ 37 แขวงดอนเมือง เขตดอนเมือง กรุงเทพมหานคร 10210",
          phone: "02-1019884",
          email: "contact@recoveryadvisor.co.th",
          align: "split",
        },
      },
      {
        id: "b_title",
        type: "doc_title",
        title: "หัวเรื่อง",
        settings: {
          titleText: "หนังสือแจ้งเปลี่ยนแปลงที่ตั้งสำนักงานใหญ่",
          subtitleText: "Notice of Head Office Relocation",
          align: "center",
        },
      },
      {
        id: "b_info",
        type: "info_grid",
        title: "ข้อมูลหนังสือ",
        settings: {
          billToTitle: "เรียน / To:",
          billToCompany: "{{recipient}}",
          attnName: "ผู้มีอุปการคุณและพันธมิตรทุกท่าน",
          subject: "{{subject}}",
          quotationNo: "TRAC-2609001",
          date: "{{doc_date}}",
          validity: "มีผล {{effective_date}}",
          amName: "ฝ่ายบริหารจัดการทั่วไป",
        },
      },
      {
        id: "b_text",
        type: "text_block",
        title: "ข้อความหนังสือแจ้ง",
        settings: {
          content: "บริษัทฯ ขอเรียนให้ท่านทราบว่า บริษัทฯ ได้ทำการย้ายและเปลี่ยนแปลงที่ตั้งสำนักงานใหญ่ โดยมีผลบังคับใช้ตั้งแต่วันที่ {{effective_date}} เป็นต้นไป ขอความกรุณาท่านโปรดใช้ที่อยู่ใหม่ในการติดต่อ ออกใบกำกับภาษี ใบเสร็จรับเงิน นิติกรรมสัญญา และการจัดส่งเอกสารต่างๆ โดยมีรายละเอียดที่อยู่ดังต่อไปนี้",
        },
      },
      {
        id: "b_terms",
        type: "terms",
        title: "เปรียบเทียบที่อยู่เดิมและใหม่",
        settings: {
          heading: "รายละเอียดสถานที่ตั้งสำนักงานใหญ่:",
          bullets: [
            "ที่อยู่เดิม: {{old_address_th}}",
            "ที่อยู่ใหม่ (มีผล {{effective_date}}): {{new_address_th}}",
            "หมายเลขโทรศัพท์และช่องทางการติดต่อทางอิเล็กทรอนิกส์ยังคงใช้งานได้ตามปกติ",
          ],
        },
      },
      {
        id: "b_signatures",
        type: "signatures",
        title: "ผู้มีอำนาจลงนาม",
        settings: {
          slots: [
            { id: "s1", name: "{{signatory_name}}", role: "{{signatory_position}}" },
          ],
        },
      },
    ],
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];
